'use client'

import { motion, useInView } from 'framer-motion'
import { useRef } from 'react'
import { SignOut, ArrowRight, ShieldCheck } from '@phosphor-icons/react'

function ScrollReveal({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  const ref = useRef<HTMLDivElement>(null)
  const isInView = useInView(ref, { once: true, margin: '-50px' })
  return (
    <motion.div ref={ref} initial={{ opacity: 0, y: 40 }} animate={isInView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.7, delay, ease: 'easeOut' }}>
      {children}
    </motion.div>
  )
}

const exitPaths = [
  { title: 'Full Capital Repayment + Interest', timeline: 'Year 1-3', detail: 'Investor capital is repaid from distributable cash flow prior to any ordinary equity dividend distributions. 20% per annum simple interest payable quarterly in arrears from operational free cash flow. Capital ranks senior to ordinary equity within the Swift Ventures SPV.', priority: 1 },
  { title: 'Production-Sharing Distribution', timeline: 'Ongoing from Year 1', detail: '60% of Net Distributable Free Cash Flow generated by the specific processing infrastructure funded. The 60/40 split operates strictly as a Production-Sharing Agreement (PSA) applying exclusively to net distributable free cash flow after OPEX, royalties, taxes, sustaining CAPEX and environmental provisions.', priority: 2 },
  { title: 'Redeemable Preference Shares', timeline: 'Year 3 maturity', detail: 'Transaction structured as Class A Redeemable Preference Shares within the Swift Ventures SPV, offering maximum tax efficiency and capital protection. This provides a clean exit mechanism at the end of the 3-year term.', priority: 3 },
  { title: 'Strategic Asset Sale', timeline: 'Optional / Post Year 3', detail: 'The mine asset portfolio may be sold to a larger mining house or institutional investor at a significant premium to invested capital, providing an additional exit route for all stakeholders.', priority: 4 },
  { title: 'Pan-African Expansion Roll-Up', timeline: 'Post Year 3', detail: 'Successful investors may elect to roll their returns into subsequent SAM mineral asset acquisitions across South Africa, Mozambique and Malawi, participating in the next phase of the Pan-African portfolio expansion.', priority: 5 },
]

export default function ExitStrategyPage() {
  return (
    <div className="space-y-12 max-w-6xl">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
        <div className="flex items-center gap-2 mb-4">
          <span className="badge badge-gold">Investment Dossier</span>
        </div>
        <h1 className="text-gold font-display font-black mb-3">Exit Strategy</h1>
        <p className="text-text-secondary text-lg font-heading italic max-w-2xl">
          Capital recovery, distribution waterfall, and investor exit pathways
        </p>
        <hr className="divider-gold mt-6" />
      </motion.div>

      <ScrollReveal>
        <section className="glass-card p-8 lg:p-10">
          <div className="flex items-center gap-3 mb-6">
            <SignOut size={24} weight="duotone" className="text-gold" />
            <h2 className="text-xl font-display font-bold text-gold">Capital Distribution Waterfall</h2>
          </div>
          <p className="text-text-muted text-xs mb-6 font-mono">Order of Priority (Senior to Junior)</p>
          <div className="space-y-3">
            {['OPEX, Royalties and Taxation', 'Senior Debt Interest (20% p.a.)', 'Investor Capital Repayment', '60% Investor Production Share', '40% Ordinary Equity Distribution'].map((item, i) => (
              <motion.div key={item} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.3 + i * 0.1, duration: 0.5 }} className="flex items-center gap-4 p-4 border border-gold/15">
                <div className="w-8 h-8 bg-gradient-to-br from-gold/30 to-gold/10 flex items-center justify-center shrink-0">
                  <span className="font-mono text-xs text-gold font-bold">{i + 1}</span>
                </div>
                <span className="text-text-primary text-sm">{item}</span>
              </motion.div>
            ))}
          </div>
        </section>
      </ScrollReveal>

      <div className="space-y-4">
        {exitPaths.map((path, i) => (
          <ScrollReveal key={path.title} delay={0.1 + i * 0.05}>
            <div className="glass-card p-6 lg:p-8">
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-3">
                  <ArrowRight size={18} weight="bold" className="text-gold shrink-0" />
                  <h3 className="text-text-primary font-body font-semibold text-sm">{path.title}</h3>
                </div>
                <span className="badge badge-gold text-[9px] shrink-0">{path.timeline}</span>
              </div>
              <p className="text-text-muted text-xs leading-relaxed">{path.detail}</p>
            </div>
          </ScrollReveal>
        ))}
      </div>

      <ScrollReveal delay={0.3}>
        <div className="glass-card p-8 lg:p-10 text-center">
          <ShieldCheck size={32} weight="duotone" className="text-gold mx-auto mb-4" />
          <h3 className="text-gold font-display font-bold text-lg mb-3">Investor Protection</h3>
          <p className="text-text-secondary text-sm max-w-2xl mx-auto leading-relaxed">
            No distributions to ordinary shareholders may occur until investor capital and contracted interest obligations have been satisfied in accordance with the agreed waterfall structure. The investor&apos;s capital shall rank senior to ordinary equity within the Swift Ventures SPV with first-ranking charge over funded processing equipment and cession of off-take receivables.
          </p>
        </div>
      </ScrollReveal>
    </div>
  )
}
